name = "nuxflare-chat-api"
main = "index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = [ "nodejs_compat", "enable_request_signal" ]

[[durable_objects.bindings]]
name = "USER"
class_name = "User"
[[durable_objects.bindings]]
name = "STREAM"
class_name = "Stream"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["User", "Stream"]

[[r2_buckets]]
binding = "BLOB"
bucket_name = "blobs"

# OpenRouter env bindings
[vars]
# Client ID and secret for OpenRouter OAuth
OPENROUTER_CLIENT_ID = ""
OPENROUTER_CLIENT_SECRET = ""
OPENROUTER_AUTH_URL = ""
OPENROUTER_TOKEN_URL = ""
OPENROUTER_USERINFO_URL = ""
OPENROUTER_REDIRECT_URI = ""

[[rules]] 
type = "Text"
globs = ["**/*.sql", "**/*.md"]
fallthrough = true
